### ISSUE TITLE
404 status in all war deployed

### ISSUE THREAD

**Issue by lokize** [cited/Tomcat-Webmin-Module#10]
Hi, thanks for this plugin is amazing, but i have a problem, all wars deployed give me this error, and i cant fix this!
![image](https://user-images.githubusercontent.com/19701630/87792486-550f6a80-c81a-11ea-804e-878958991601.png)

**Comment by DavidGhedini** [comment]
Hi -
Does the url include :8080 or is it behind a proxy?
Also, what does the logs say at /home/tomcat/tomcat-xx/logs?
David

**Comment by lokize** [comment]
thanks for help, i think a make a mistake, how to completely uninstall and resintall the tomcat module? 
![image](https://user-images.githubusercontent.com/19701630/87815957-e68fd400-c83c-11ea-9536-38a302e2bf90.png)

**Comment by lokize** [comment]
i make a clean tomcat installation, but i cant make work with module...

**Comment by lokize** [comment]
i try now reinstalling module and i have this error: 
![image](https://user-images.githubusercontent.com/19701630/87831878-0a621280-c85b-11ea-9d40-ccfdf4b64aa4.png)

**Comment by lokize** [comment]
hello good morning, sorry if I'm being insistent I would really like this to work, it seems that he can't find the tomcat to download so the module has problems? Could you help me, please

**Comment by DavidGhedini** [comment]
Hi -
1. What is the OS you are using?
2. Where are you downloading the Tomcat plugin from?
David

**Comment by lokize** [comment]
thanks! Ubuntu 20.04 LTS, downloaded from this github page in webmin modules - url : http://github.com/cited/Tomcat-Webmin-Module/raw/master/scripts/tomcat.wbm.gz

**Comment by lokize** [comment]
is there any way to completely uninstall and reinstall the module?

**Comment by DavidGhedini** [comment]
Yes, go to Webmin > Configuration > Webmin Modules.  Select the module and delete it.  Then re-install it.

**Comment by kaloyan13** [comment]
Are you running as the root user in Webmin ?
/etc/init.d/tomcat: not found

> thanks for help, i think a make a mistake, how to completely uninstall and resintall the tomcat module?
> ![image](https://user-images.githubusercontent.com/19701630/87815957-e68fd400-c83c-11ea-9536-38a302e2bf90.png)

This means service file was not installed. The only reason I see is not enough permissions.
Are you running as the root user in Webmin ?

**Comment by lokize** [comment]
yes root user, i try reinstalling, but not work...

**Comment by kaloyan13** [comment]
> Yes, go to Webmin > Configuration > Webmin Modules. Select the module and delete it. Then re-install it.
That is the way to uninstall.
Did you execute every step of the setup process ?

**Comment by lokize** [comment]
yes, i make a clean installation of a centos now, and i cant stop tomcat or deploy a war, seems a permission problem 
![image](https://user-images.githubusercontent.com/19701630/87950890-445f2e80-ca7e-11ea-8355-9d52eaa1cf7b.png)

**Comment by lokize** [comment]
ok I got it, first I would like to thank you for your help, what I did was install tomcat and migrate the settings to the module, everything worked ok, just the 404 message that tomcat was not found on the main screen of the module, probably because the script address is not being found to download tomcat, anyway everything worked out, thanks!
