### ISSUE TITLE
Ubuntu 20 and Tomcat 9 - unable to detect existing installation

### ISSUE THREAD

**Issue by red-erik** [cited/Tomcat-Webmin-Module#11]
Hello,
thank you for your great work.
I'm not a Linux expert but, every combination I try on module configuration path I'm not able to have Webmin Tomcat Module correctly detect existing Tomcat 9 installation and status.
Any suggestion will be greatly appreciated.
Regards,
Red.

My Tomcat service (in Webmin BootUp/Shutdown) is the following:
#
# Systemd unit file for Apache Tomcat
#

[Unit]
Description=Apache Tomcat 9 Web Application Server
Documentation=https://tomcat.apache.org/tomcat-9.0-doc/index.html
After=network.target
RequiresMountsFor=/var/log/tomcat9 /var/lib/tomcat9

[Service]

# Configuration
Environment="CATALINA_HOME=/usr/share/tomcat9"
Environment="CATALINA_BASE=/var/lib/tomcat9"
Environment="CATALINA_TMPDIR=/tmp"
Environment="JAVA_OPTS=-Djava.awt.headless=true"

# Lifecycle
Type=simple
ExecStartPre=+/usr/libexec/tomcat9/tomcat-update-policy.sh
ExecStart=/bin/sh /usr/libexec/tomcat9/tomcat-start.sh
SuccessExitStatus=143
Restart=on-abort

# Logging
SyslogIdentifier=tomcat9

# Security
User=tomcat
Group=tomcat
PrivateTmp=yes
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
CacheDirectory=tomcat9
CacheDirectoryMode=750
ProtectSystem=strict
ReadWritePaths=/etc/tomcat9/Catalina/
ReadWritePaths=/var/lib/tomcat9/webapps/
ReadWritePaths=/var/log/tomcat9/

[Install]
WantedBy=multi-user.target

**Comment by kaloyan13** [comment]
The module expects all Tomcat directories to be under a single parent directory.
The easiest thing you can try is:

#Add the environment variable
echo 'CATALINA_HOME=/home/tomcat/apache-tomcat-9.0.0/' >> /etc/environment

# Create a CATALINA_HOME with links
export CATALINA_HOME=/home/tomcat/apache-tomcat-9.0.0 
mkdir-p /home/tomcat/apache-tomcat-9.0.0/
ln -s /var/lib/tomcat9/webapps/ ${CATALINA_HOME}/webapps
ln -s /var/log/tomcat9/ ${CATALINA_HOME}/logs
ln -s /etc/tomcat9/Catalina/ ${CATALINA_HOME}/conf
ln -s /usr/libexec/tomcat9 ${CATALINA_HOME}/bin

# overwrite the service file, to use your systemctl service
echo 'systemctl $1 tomcat' >/etc/init.d/tomcat.service

Don't change the config.

**Comment by red-erik** [comment]
Hello,
tried but have some problem with the service, not detected as started. As I'm not a Linux expert, would you be so kind to explain me in detail what to do for the service configuration?
Thank you in advance.
Regards,
Red.

**Comment by red-erik** [comment]
Hello,
I modified 
`echo 'systemctl $1 tomcat' >/etc/init.d/tomcat.service` to
`echo 'systemctl $1 tomcat9' >/etc/init.d/tomcat` and now I have the same result of issue #9 

● tomcat9.service - Apache Tomcat 9 Web Application Server Loaded: loaded (/lib/systemd/system/tomcat9.service; enabled; vendor preset: enabled) Active: active (running) since Fri 2020-11-06 13:09:12 UTC; 3 days ago Docs: https://tomcat.apache.org/tomcat-9.0-doc/index.html Process: 27490 ExecStartPre=/usr/libexec/tomcat9/tomcat-update-policy.sh (code=exited, status=0/SUCCESS) Main PID: 27509 (java) Tasks: 44 (limit: 4620) Memory: 368.7M CGroup: /system.slice/tomcat9.service └─27509 /usr/lib/jvm/default-java/bin/java -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/share/tomcat9/bin/bootstrap.jar:/usr/share/tomcat9/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat9 -Dcatalina.home=/usr/share/tomcat9 -Djava.io.tmpdir=/tmp org.apache.catalina.startup.Bootstrap start Nov 06 13:49:01 rmguacp02 tomcat9[27509]: 13:49:01.692 [http-nio-8080-exec-2] INFO o.a.g.environment

The module propose me to "start" Tomcat while already running.

Regards,
Red.

**Comment by kaloyan13** [comment]
I have updated my previous post. Change only the /etc/init.d/tomcat file content, and make it executable.

**Comment by red-erik** [comment]
Hello,
it works like a charm, thank you very much but, in the center of the module, under "Tomcat Server" i see:
Tomcat 0 / Java unknown 
Is it normal or I need to modify something else ?
Thank you again for your help.

Regards,

Red.

**Comment by kaloyan13** [comment]
Try #12 
I tested on Ubuntu 20 with Tomcat 9.0.37 and JDK11, and it worked.

**Comment by red-erik** [comment]
Hello,
I installed the module (over previous installation) but with same "cosmetic" problem.
Should I remove it and install from scratch ?
Regards,

Red.

**Comment by kaloyan13** [comment]
Update the bin link to
ln -sf /usr/share/tomcat9/bin/ ${CATALINA_HOME}/bin

**Comment by red-erik** [comment]
Hello,
no changes but I can't reboot the server now.
Regards,

Red.

**Comment by kaloyan13** [comment]
The lib dir and temp were missing.
```
mkdir -p /home/tomcat/apache-tomcat-9.0.0/temp
ln -s /usr/share/tomcat9/lib ${CATALINA_HOME}/lib
```

**Comment by red-erik** [comment]
Hello,
same result, even after a reboot.
Do you mean to create both ? Like:
`mkdir -p /home/tomcat/apache-tomcat-9.0.0/temp
ln -s /usr/share/tomcat9/temp ${CATALINA_HOME}/temp`
`mkdir -p /home/tomcat/apache-tomcat-9.0.0/lib
ln -s /usr/share/tomcat9/lib ${CATALINA_HOME}/lib`
Regards,
Red.

**Comment by red-erik** [comment]
Hello,
I'm closing the issue because I did not receive further help.
Thank you for your work.
Regards,

Red.
