### ISSUE TITLE
only shows versions 6, 7, 8, 9 how to make it show v10

### ISSUE THREAD

**Issue by pieter-groeneweg** [cited/Tomcat-Webmin-Module#16]
I stumbled upon your module. 
I have a webmin 1999 on debian 10, tomcat 10..

However 10 is not detected. Instead I am asked to install 
When I follow the 'lead' I only see 9 and down to 6.

In code of tomcat-lib.pl I can see it gets the info from the apache URL..
But I cannot see why it only sees 6, 7, 8, 9 as in line 308.
There are more versions in https://archive.apache.org/dist/tomcat/

I may be overlooking things, but how would I be able to include v10?

Tx,

**Comment by kaloyan13** [comment]
We parse the versions from [Apache archive website](https://archive.apache.org/dist/tomcat/) in https://github.com/cited/Tomcat-Webmin-Module/blob/63cd2c0d33b0df4c293a30d0b8d06b4cae6b5e7f/tomcat-lib.pl#L282

I tested the code outside of module and it works.

**Comment by kaloyan13** [comment]
Just tested with master and it works.
![image](https://user-images.githubusercontent.com/5628521/185587501-0a076997-f159-40b8-be07-39889924f730.png)

**Comment by pieter-groeneweg** [comment]
Tjeez.. now you may call me stupid for overlooking the obvious. ;)

I added the 10, but am stuck at errormessage "Error: HTTP/1.1 404 Not Found"

I am afraid it looks for a single digit version

**Comment by kaloyan13** [comment]
It works on Debian 11.
Are you using the latest code ?

**Comment by pieter-groeneweg** [comment]
I used the webmin module install method... but that appears older than the code here..

**Comment by pieter-groeneweg** [comment]
It did work using the module on GitHub.. not the one that pops up in Webmin/

**Comment by DavidGhedini** [comment]
Please try it again now.  It looks like you were using the pre-built module in the scripts directory.  It's now been updated.

**Comment by DavidGhedini** [comment]
Closing
