### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by livadiotis** [cited/Tomcat-Webmin-Module#17]
I first installed tomcat 10. I tried to uninstall to install tomcat 9 it by deleting the home/tomcat folder and rerun the setup. The setup screen does not appear and automatically installs tomcat 10.
How can i perform a clean install so i can select tomcat 9?

**Comment by kaloyan13** [comment]
1. Delete /home/tomcat/apache-tomcat-10.x.x
2. Delete CATALINA_HOME and CATALINA_BASE from /etc/environment
3. Delete tomcat user from system
4. Download and copy setup.cgi from repot to webmin module dir (/usr/libexec/webmin/tomcat/ on CetnOS).

**Comment by livadiotis** [comment]
Thank you!
