### ISSUE TITLE
Error: update-alternatives

### ISSUE THREAD

**Issue by boboz** [cited/Tomcat-Webmin-Module#18]
Hey,

Set up this lovely module but java install would not complete as I got an "Error: update-alternatives" at the end. Tried reinstall and also tried update-alternatives manually but to no avail. Scratched the instance and then installed java manually (sudo apt install default-jdk). After that everything installed/worked as expected. Screenshot attached.

![screenshot-129 151 209 209_10000-2023 01 04-17_32_32](https://user-images.githubusercontent.com/141707/210632096-964afa2a-1de3-4cdc-9ca7-fc7dbadbc2f0.png)

**Comment by DavidGhedini** [comment]
What is the exact Operating System?

**Comment by boboz** [comment]
Ubuntu Linux 22.04.1

**Comment by DavidGhedini** [comment]
I'm not able to replicate this.  I installed on Ubuntu 22.04.1 and was able to install Java via the Java tab.
I installed JDK 19 as well as 8 and 11 and no issues were encountered.

**Comment by boboz** [comment]
Hm.. the instance is a Arm Ampere A1 core CPU at Oracle Cloud. Could that interfere somehow? I'll set up an AMD based instance and se what happens.

Thank you for quick response
/B

**Comment by DavidGhedini** [comment]
I'm not familiar with their setup.  All of our modules are tested on vanilla Operating Systems.
