### ISSUE TITLE
Error after install - PERL execution failed

### ISSUE THREAD

**Issue by GriffinNBTS** [cited/Tomcat-Webmin-Module#20]
After installing the TomCat module, I get this error:

----------
HTTP/1.0 500 Perl execution failed Server: MiniServ/2.021 Date: Mon, 24 Jul 2023 19:18:53 GMT Content-type: text/html; Charset=utf-8 Connection: close
ERROR — PERL EXECUTION FAILED
Undefined subroutine &software::package_info called at /usr/libexec/webmin/tomcat/setup.cgi line 182.
----------

I have tried uninstalling & reinstalling several times, from Webmin Module install and from the install script, but I always get the same error.

I am trying to use this on Amazon Linux2, freshly created a week ago, so it is the latest version (based on RHEL and CentOS, I believe). I have Webmin running fine, and I have an existing TomCat server (v10.1.11) installed at /home/tomcat/tomcat which also works fine.

I would appreciate any help to get this working!

Thank you!
Griffin

**Comment by DavidGhedini** [comment]
Its looking for the Epel repo to install haveged.

**Comment by GriffinNBTS** [comment]
I tried installing epel repo from the instructions for installing the tomcat module, but it did not work:

----
[root@ip-172-31-23-225 /]# yum install epel-release
Last metadata expiration check: 2:42:44 ago on Mon Jul 24 19:59:54 2023.
No match for argument: epel-release
Error: Unable to find a match: epel-release
----

I also tried installing it using instructions from the link below, but none of those instructions worked either:

https://www.liquidweb.com/kb/enable-epel-repository/

I tried to install haveged, but it also failed:

----
yum install haveged
Last metadata expiration check: 2:42:59 ago on Mon Jul 24 19:59:54 2023.
No match for argument: haveged
Error: Unable to find a match: haveged
----
If there are other ways to install epel repo & haveged, could you please let me know?

Thank you for your help with this!
Griffin

**Comment by GriffinNBTS** [comment]
After a little more digging, I discovered I am using Amazon Linux 2023, not Linux2. I originally installed Linux2, but I also installed a Linux 2023 instance, and apparently I used the Linux 2023 instance for my tomcat install. According to this KB article from AWS, EPEL cannot be installed on Linux 2023:
https://repost.aws/knowledge-center/ec2-enable-epel

So, is there a workaround for this, that will work on Linux 2023, or will the TomCat module just not work on Linux 2023?

Thanks again,
Griffin

**Comment by DavidGhedini** [comment]
You can just comment out the epel section (lines 182 to 194:

`my @pinfo = software::package_info('haveged', undef, );
	if(!@pinfo){
		my %osinfo = &detect_operating_system();
		if( $osinfo{'real_os_type'} =~ /centos/i){	#CentOS
			@pinfo = software::package_info('epel-release', undef, );
			if(!@pinfo){
				print "<p>Warning: haveged needs epel-release. Install it manually or ".
						"<a href='../package-updates/update.cgi?mode=new&source=3&u=epel-release&redir=%2E%2E%2Ftomcat%2Fsetup.cgi&redirdesc=Tomcat Setup'>click here</a> to have it downloaded and installed.</p>";
			}
		}
		print "<p>Warning: haveged package is not installed. Install it manually or ".
			  "<a href='../package-updates/update.cgi?mode=new&source=3&u=haveged&redir=%2E%2E%2Ftomcat%2Fsetup.cgi&redirdesc=Tomcat Setup'>click here</a> to have it downloaded and installed.</p>";
	}`

**Comment by GriffinNBTS** [comment]
The line numbers are my system appear to be different. If i comment out lines 182-194, that comments out in the middle of an if section, and webmin breaks. Here is the code in my setup.cgi:

----
180
181  sub setup_checks{
182
183	#Check for commands
184	if (!&has_command('java')) {
185		print '<p>Warning: Java is not found. Install it manually or from the '.
186			  "<a href='./edit_java.cgi?return=%2E%2E%2Ftomcat%2Fsetup.cgi&returndesc=
Setup&caller=tomcat'>Java tab</a></p>";
187	}
188
189	my @pinfo = software::package_info('haveged', undef, );
190	if(!@pinfo){
191		my %osinfo = &detect_operating_system();
192		if( $osinfo{'real_os_type'} =~ /centos/i){	#CentOS
193			@pinfo = software::package_info('epel-release', undef, );
194			if(!@pinfo){
195				print "<p>Warning: haveged needs epel-release. Install it manually or ".
196						"<a href='../package-updates/update.cgi?mode=new&source=3&u=epel-release&redir=%2E%2E%2Ftomcat%2Fsetup.cgi&redirdesc=Tomcat Setup'>click here</a> to have it downloaded and installed.</p>";
197			}
198		}
199		print "<p>Warning: haveged package is not installed. Install it manually or ".
200			  "<a href='../package-updates/update.cgi?mode=new&source=3&u=haveged&redir=%2E%2E%2Ftomcat%2Fsetup.cgi&redirdesc=Tomcat Setup'>click here</a> to have it downloaded and installed.</p>";
201	}
----

I tried commenting out lines 189-201, which appear to remove the check for haveged, but then webmin triggers the same PERL error, but at line 225, which is:

----
225   @pinfo = software::package_info($www_name, undef, );
226 if(!@pinfo){
227		print "<p>Warning: $www_name is not installed. Install it manually or ".
228				"<a href='../package-updates/update.cgi?mode=new&source=3&u=$www_name&redir=%2E%2E%2Ftomcat%2Fsetup.cgi&redirdesc=Tomcat Setup'>click here</a> to have it downloaded and installed.</p>";
229	}
----

When I comment out line 225, I get all kinds of config errors when i try to run the tomcat module.

Based on my line numbers, what lines should be commented out?

In trying to find an alternate way to install haveged, I found a comment from the haveged developer who says that haveged is no longer necessary for modern kernels. which may be why it is not installable in AWS Linux 2023:
https://github.com/jirka-h/haveged/issues/57

Perhaps haveged should be an optional install for the tomcat module?

**Comment by DavidGhedini** [comment]
Use the line numbers from https://github.com/cited/Tomcat-Webmin-Module/blob/master/setup.cgi
You are just commenting out the function that looks for haveged via epel.

**Comment by GriffinNBTS** [comment]
I reinstalled the entire module, then the line numbers in setup.cgi matched up with what you referenced. I commented them out and got the same results - another PERL error, now at line 218 (with the same code that was at 225 before). I commented out line 218, and was able to get to the continue setup page, but with a few errors. I clicked on continue as though there were no errors and the TomCat module then loaded. But I have a couple of errors on the module, and I can't edit the config, or stop/start tomcat, or really do anything at all. It shows:

Fatal Error!
Failed to install module from https://archive.apache.org/dist/tomcat/tomcat-tomcat/ : HTTP/1.1 404 Not Found
Unit tomcat.service could not be found.

I edited the /etc/webmin/tomcat/config file to point to my installation of tomcat (/home/tomcat/tomcat) but i still get the same errors on the TomCat module.

When I try to use 'Edit config' button, it tries to open the config files at /home/tomcat/apache-tomcat-apache/bin which does not exist, and there does not seem to be a way to change where it thinks the config files are.

So, still no functionality.

Do you have any other suggestions?

**Comment by DavidGhedini** [comment]
I'm not at all familiar with the AWS linux distro you are using.
You'll need to adjust it to your setup.
The files are all located in the /usr/libexec/webmin/tomcat directory.
You can get the filename in use from the url when clicking on the component.
