### ISSUE TITLE
Config Module with existing Tomcats

### ISSUE THREAD

**Issue by mohamed-khadragy** [cited/Tomcat-Webmin-Module#21]
The readme file doesn't show up how to configure the module to point out to the existing tomcat.
it stated that I need to do this configs manually but with zero guidance.

**Comment by DavidGhedini** [comment]
https://github.com/cited/Tomcat-Webmin-Module?tab=readme-ov-file#existing-tomcat-installations

1. Click config icon in top left corner of module.
2. Set the paths to those used on your installation (replace paths with your own Tomcat paths)
3. Once you have updated the /etc/webmin/tomcat/config file to your installation paths, you should be able to use all functionality.

**Comment by mohamed-khadragy** [comment]
Can you share an example for this
the  /etc/webmin/tomcat/config file contains only a single line that points to itself. I tried to add the path to config files of my tomcat but the module still search for the default path.

My question is how to modify th defaults settings (with example if available) to
- point to the new config files
- point to the correct service name (different than tomcat.service)
- point to different base directory for tomcat (example /tomcat/tomcat10)

**Comment by DavidGhedini** [comment]
You need to click the Config icon on the top left of the module

![image](https://github.com/cited/Tomcat-Webmin-Module/assets/655540/ccaa037f-9049-42b1-ab2a-045bdb689464)
