### ISSUE TITLE
Java Not Found

### ISSUE THREAD

**Issue by avaramis** [cited/Tomcat-Webmin-Module#5]
Hi I was/am excitied to use your Tomcat plugin as it will hopefully enable me to restart tomcat from my phone if things go wrong while prototyping.
The setup is incomplete stating that:
Warning: Java is not found. Install it manually or from the Java tab
![image](https://user-images.githubusercontent.com/12189363/74668669-b2bc5f80-5173-11ea-8014-682ba5a19257.png)

When I follow the link to the "java tab" I have:

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.941 Date: Mon, 17 Feb 2020 15:53:50 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

open:No such file or directory at ./java-lib.pl line 118. 

I can take a shot at installing Java manually but pushbutton maintenance is nice for somebody as time constrained as myself.

This is a really great idea thanks for making it :)

**Comment by avaramis** [comment]
I was able to install a jdk manually and get this working, but this guy gets 2x as good if I can automate java updates through webmin too. 
I don't know if I'd have gotten that or not but since we were updating java vulnerabilities every other day at work for a while then webmin updates & java would be an epic time saver :)

**Comment by DavidGhedini** [comment]
This has been fixed by @kaloyan13
