### ISSUE TITLE
Map domains to Tomcat applications

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [cited/Tomcat-Webmin-Module#7]
Hi! Thanks for your module. It's very helpful.
But I have on question. How ca I map some domain with tomcat application?

Thanks for your help.

**Comment by DavidGhedini** [comment]
It isn't something peculiar to the module. You could use Apache as reverse proxy or ajp, etc..
`
<VirtualHost   *:80>
--
ServerName yourdomain.com

 
ProxyRequests Off
ProxyPreserveHost On
<Proxy *>
Order allow,deny
Allow from all
</Proxy>
 
ProxyPass / http://localhost:8080/
ProxyPassReverse /   http://localhost:8080/
</VirtualHost>
`

**Comment by ChafikHadjAbdouRazack** [comment]
OK. Thank you.
