### ISSUE TITLE
Tomcat status not correctly detected

### ISSUE THREAD

**Issue by vagodoy** [cited/Tomcat-Webmin-Module#9]
I have installed Tomcat 8 in an Ubuntu 16.04 distribution with  "sudo apt-get install tomcat8".
I later installed the Webmin module and changed the config file to:

tomcat_config=/etc/webmin/tomcat/config
tomcat_service=/etc/init.d/tomcat8

However the Webmin does not correctly detect the status of the Tomcat server. It offers me the Start server button when the service is up an running.

**Comment by vagodoy** [comment]
![image](https://user-images.githubusercontent.com/39992986/78870730-e2d30100-7a46-11ea-9bee-5e02030a96c6.png)

**Comment by DavidGhedini** [comment]
Checking this now...

**Comment by DavidGhedini** [comment]
Is this still an issue?

**Comment by DavidGhedini** [comment]
Closing as OP did not reply.
